name: Merge Pull Request
on: pull_request
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Start:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: merge
        run: |
          gh pr merge ${{ github.ref_name }} -m -d