name: Merge Pull Request
on: pull_request
env:
  GH_TOKEN: ${{ secrets.GH_WORKFLOW_TOKEN }}
jobs:
  Start:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: merge
        run: |
          gh pr merge ${{ github.head_ref }} -m -d