name: Merge Pull Request
on: pull_request
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  Start:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: merge
        run: |
          echo ${{ github.ref_name }}
          gh pr merge ${{ github.ref_name }} -m -d