name: Merge Pull Request
on: pull_request
jobs:
  Start:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: generate token
        id: get-token-app
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET }}
      - name: merge
        env:
          GH_TOKEN: ${{ steps.get-token-app.outputs.token }}
        run: |
          gh pr merge ${{ github.head_ref }} -m -d